name: Terraform AWS EC2

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:   # 👈 Make credentials available to all steps
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: .

      - name: Terraform Plan
        run: terraform plan
        working-directory: .

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: .
    